on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-job1:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: test-step1
        run: |
          pwd
          ls -al
          cat values.yml
          echo ${{ vars.IMAGE_REPOSITORY }}
          
